[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hypermedia-server"
version = "0.0.1"
authors = [
  { name="Plain Concepts Research"},
]
description = "hypermedia-systems"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://github.com/pypa/hypermedia-server"
Issues = "https://github.com/pypa/hypermedia-server/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/hypermedia_server"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.coverage.run]
omit = [
  "tests/*",
]
source = [
  "src/hypermedia_server"
]
relative_files = true

[tool.coverage.report]
skip_empty = true

[tool.coverage.paths]
source = [
    "src/hypermedia_server",
    "tests/"
]

[tool.isort]
profile = 'black'
